export const typographyTokens = {
  fontFamily: {
    ui: "'Bree 2', 'Sofia Sans Semi Condensed', 'Lufga', 'Lexend', system-ui, sans-serif",
    emphasis: "'Bree 2', 'Sofia Sans', 'Sofia Sans Semi Condensed', 'Lufga', 'Lexend', system-ui, sans-serif",
    brand: "'Bree 2', 'Sofia Sans', 'Sofia Sans Semi Condensed', 'Lufga', 'Lexend', system-ui, sans-serif",
    mono: "'JetBrains Mono', 'IBM Plex Mono', monospace",
  },
  fontSize: {
    xs: '0.9167rem',
    sm: '1.0417rem',
    md: '1.1667rem',
    lg: '1.2917rem',
    xl: '1.4167rem',
    '2xl': '1.6667rem',
    '3xl': '2.0417rem',
    '4xl': '2.4167rem',
    '5xl': '3.1667rem',
    controlLabel: '0.8125rem',
    supporting: '0.875rem',
    chatContent: '0.9375rem',
  },
  fontWeight: {
    regular: 400,
    medium: 700,
    semibold: 700,
    bold: 700,
    black: 700,
  },
  lineHeight: {
    xs: 1.35,
    sm: 1.4,
    md: 1.5,
    lg: 1.6,
    xl: 1.15,
  },
  letterSpacing: {
    tight: '0em',
    normal: '0em',
    wide: '0.02em',
  },
  textStyle: {
    caption: {
      fontSize: '0.75rem',
      lineHeight: 1.35,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    small: {
      fontSize: '0.875rem',
      lineHeight: 1.4,
      fontWeight: 400,
      letterSpacing: '0em',
    },
    bodySm: {
      fontSize: '0.875rem',
      lineHeight: 1.4,
      fontWeight: 400,
      letterSpacing: '0em',
    },
    body: {
      fontSize: '1rem',
      lineHeight: 1.5,
      fontWeight: 400,
      letterSpacing: '0em',
    },
    bodyLg: {
      fontSize: '1.125rem',
      lineHeight: 1.6,
      fontWeight: 400,
      letterSpacing: '0em',
    },
    titleSm: {
      fontSize: '1.125rem',
      lineHeight: 1.2,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    titleMd: {
      fontSize: '1.5rem',
      lineHeight: 1.15,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    titleLg: {
      fontSize: '1.875rem',
      lineHeight: 1.15,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    h1: {
      fontSize: '2rem',
      lineHeight: 1.1,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    h2: {
      fontSize: '1.5rem',
      lineHeight: 1.15,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    h3: {
      fontSize: '1.125rem',
      lineHeight: 1.25,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    display: {
      fontSize: '3rem',
      lineHeight: 1,
      fontWeight: 700,
      letterSpacing: '0em',
    },
  },
} as const

export type TypographyTokens = typeof typographyTokens
