export const typographyTokens = {
  fontFamily: {
    ui: "'Inter', system-ui, -apple-system, sans-serif",
    emphasis: "'Plus Jakarta Sans', 'Inter', system-ui, -apple-system, sans-serif",
    brand: "'Plus Jakarta Sans', 'Inter', system-ui, -apple-system, sans-serif",
    mono: "'JetBrains Mono', 'IBM Plex Mono', monospace",
  },
  fontSize: {
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '0.875rem',
    xl: '1rem',
    '2xl': '1.25rem',
    '3xl': '1.625rem',
    '4xl': '2rem',
    '5xl': '2.75rem',
    controlLabel: '0.6875rem',
    supporting: '0.75rem',
    chatContent: '0.7708rem',
  },
  fontWeight: {
    regular: 400,
    medium: 700,
    semibold: 700,
    bold: 700,
    black: 700,
  },
  lineHeight: {
    xs: 1.35,
    sm: 1.4,
    md: 1.5,
    lg: 1.6,
    xl: 1.15,
  },
  letterSpacing: {
    tight: '0em',
    normal: '0em',
    wide: '0.02em',
  },
  textStyle: {
    caption: {
      fontSize: '0.75rem',
      lineHeight: 1.35,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    small: {
      fontSize: '0.875rem',
      lineHeight: 1.4,
      fontWeight: 400,
      letterSpacing: '0em',
    },
    bodySm: {
      fontSize: '0.875rem',
      lineHeight: 1.4,
      fontWeight: 400,
      letterSpacing: '0em',
    },
    body: {
      fontSize: '1rem',
      lineHeight: 1.5,
      fontWeight: 400,
      letterSpacing: '0em',
    },
    bodyLg: {
      fontSize: '1.125rem',
      lineHeight: 1.6,
      fontWeight: 400,
      letterSpacing: '0em',
    },
    titleSm: {
      fontSize: '0.9583rem',
      lineHeight: 1.2,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    titleMd: {
      fontSize: '1.3333rem',
      lineHeight: 1.15,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    titleLg: {
      fontSize: '1.7083rem',
      lineHeight: 1.15,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    h1: {
      fontSize: '1.5833rem',
      lineHeight: 1.1,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    h2: {
      fontSize: '1.0833rem',
      lineHeight: 1.15,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    h3: {
      fontSize: '0.7083rem',
      lineHeight: 1.25,
      fontWeight: 700,
      letterSpacing: '0em',
    },
    display: {
      fontSize: '2.8333rem',
      lineHeight: 1,
      fontWeight: 700,
      letterSpacing: '0em',
    },
  },
} as const

export type TypographyTokens = typeof typographyTokens
