from sqlalchemy import Column, String, Enum, DateTime, Boolean, ForeignKey, func, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
import uuid

from app.core.database import Base
from app.models.enums import UserRole, TeacherRequestStatus


class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=True, index=True)
    email = Column(String, nullable=True, index=True)
    password_hash = Column(String, nullable=True)
    role = Column(Enum(UserRole), nullable=False)
    first_name = Column(String, nullable=True)
    last_name = Column(String, nullable=True)
    institution = Column(String, nullable=True)
    avatar_url = Column(Text, nullable=True)
    ui_accent = Column(String(32), nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    deactivated_at = Column(DateTime(timezone=True), nullable=True)
    deactivated_by_admin_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True, index=True)
    is_verified = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    last_login_at = Column(DateTime(timezone=True), nullable=True)
    preferences_json = Column(JSONB, default=dict, nullable=False, server_default='{}')
    # preferences_json stores: { default_model, last_session_id, last_chat_session_id, ui_settings }
    support_chat_system_prompt = Column(Text, nullable=True)
    # Custom system prompt for teacher's own AI assistant (overrides default if set)
    is_school_owner = Column(Boolean, default=False, nullable=False, server_default="false")
    # True for the primary contact of a SCHOOL tenant — can invite colleagues

    # Relationships
    tenant = relationship("Tenant", back_populates="users", foreign_keys=[tenant_id])
    classes = relationship("Class", back_populates="teacher", lazy="dynamic")
    reviewed_requests = relationship("TeacherRequest", back_populates="reviewed_by_admin", lazy="dynamic")
    legal_acceptances = relationship("LegalDocumentAcceptance", back_populates="user", lazy="dynamic", cascade="all, delete-orphan")


class LegalDocumentAcceptance(Base):
    __tablename__ = "legal_document_acceptances"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=True, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    document_key = Column(String(64), nullable=False, index=True)
    document_title = Column(String(180), nullable=False)
    document_version = Column(String(64), nullable=False)
    accepted_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    ip_address = Column(String(64), nullable=True)
    user_agent = Column(Text, nullable=True)

    user = relationship("User", back_populates="legal_acceptances")
    tenant = relationship("Tenant")

    __table_args__ = (
        UniqueConstraint("user_id", "document_key", "document_version", name="uq_legal_acceptance_user_doc_version"),
    )


class TeacherRequest(Base):
    __tablename__ = "teacher_requests"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True)
    email = Column(String, nullable=False)
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    status = Column(Enum(TeacherRequestStatus), default=TeacherRequestStatus.PENDING, nullable=False)
    reviewed_by_admin_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    tenant = relationship("Tenant")
    reviewed_by_admin = relationship("User", back_populates="reviewed_requests")


class PasswordResetToken(Base):
    """Token for self-service password reset (generated by admin, used by teacher)"""
    __tablename__ = "password_reset_tokens"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    token = Column(String(64), nullable=False, unique=True, index=True)
    is_used = Column(Boolean, default=False, nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    used_at = Column(DateTime(timezone=True), nullable=True)

    user = relationship("User")


class ActivationToken(Base):
    """Token for teacher account activation with temporary password"""
    __tablename__ = "activation_tokens"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    token = Column(String(64), nullable=False, unique=True, index=True)
    temporary_password = Column(String, nullable=False)
    is_used = Column(Boolean, default=False, nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    used_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    user = relationship("User")
