#!/usr/bin/env node
/**
 * Generates src/components/icons/icons.generated.tsx from the official Phosphor SVGs (@phosphor-icons/core).
 *
 * Only the icons listed in src/components/icons/icon-map.json are emitted, in a single weight, so the bundle
 * carries ~340 small glyphs instead of every weight of every icon.
 *
 *   node scripts/generate-icons.mjs                # Flaticon UIcons solid-rounded (default)
 *   node scripts/generate-icons.mjs --set phosphor # Phosphor SVGs, default weight fill
 *   node scripts/generate-icons.mjs --weight fill  # restyle the whole platform
 *
 * To add an icon: add "ExportName": "PhosphorName" to icon-map.json and run `npm run icons`.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const WEIGHTS = ['thin', 'light', 'regular', 'bold', 'fill', 'duotone']
const weightArg = process.argv.indexOf('--weight')
const weight = weightArg > -1 ? process.argv[weightArg + 1] : 'fill'

const setArg = process.argv.indexOf('--set')
const iconSet = setArg > -1 ? process.argv[setArg + 1] : 'uicons'
if (iconSet === 'uicons') {
  // Flaticon UIcons webfont (solid, rounded): icon-map.uicons.json maps export name → uicons class suffix.
  const umap = JSON.parse(readFileSync(join(root, 'src/components/icons/icon-map.uicons.json'), 'utf8'))
  const out = [
    '// AUTO-GENERATED by scripts/generate-icons.mjs --set uicons — do not edit. Change icon-map.uicons.json and run `npm run icons`.',
    '// Flaticon UIcons (https://www.flaticon.com/uicons), solid rounded. Attribution required: see the credits page.',
    "import { createFontIcon } from './createFontIcon'",
    '',
    ...Object.entries(umap)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([n, g]) => `export const ${n} = createFontIcon('${n}', '${g}')`),
    '',
  ]
  writeFileSync(join(root, 'src/components/icons/icons.generated.tsx'), out.join('\n'))
  console.log(`Generated ${Object.keys(umap).length} UIcons icons.`)
  process.exit(0)
}

if (iconSet === 'phosphor' && !WEIGHTS.includes(weight)) {
  console.error(`Unknown weight "${weight}". Use one of: ${WEIGHTS.join(', ')}`)
  process.exit(1)
}

const assets = join(root, 'node_modules/@phosphor-icons/core/assets', weight)
const map = JSON.parse(readFileSync(join(root, 'src/components/icons/icon-map.json'), 'utf8'))

// PascalCase Phosphor name → kebab-case asset file ("TextHOne" → "text-h-one", "ArrowUUpLeft" → "arrow-u-up-left").
const kebab = (name) => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([A-Z])([A-Z])/g, '$1-$2').toLowerCase()

const bodies = new Map()
const missing = []
for (const phosphorName of new Set(Object.values(map))) {
  const suffix = weight === 'regular' ? '' : `-${weight}`
  const file = join(assets, `${kebab(phosphorName)}${suffix}.svg`)
  if (!existsSync(file)) {
    missing.push(`${phosphorName} (${file})`)
    continue
  }
  const svg = readFileSync(file, 'utf8')
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
  bodies.set(phosphorName, inner)
}
if (missing.length) {
  console.error(`Missing Phosphor assets:\n  ${missing.join('\n  ')}`)
  process.exit(1)
}

const glyphConst = (phosphorName) => `G_${phosphorName}`
const lines = [
  '// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit. Change icon-map.json and run `npm run icons`.',
  `// Phosphor Icons (https://phosphoricons.com, MIT), weight: ${weight}.`,
  "import { createIcon } from './createIcon'",
  '',
  `export const ICON_WEIGHT = '${weight}'`,
  '',
  ...[...bodies.entries()].map(([name, body]) => `const ${glyphConst(name)} = ${JSON.stringify(body)}`),
  '',
  ...Object.entries(map)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([exportName, phosphorName]) => `export const ${exportName} = createIcon('${exportName}', ${glyphConst(phosphorName)})`),
  '',
]
writeFileSync(join(root, 'src/components/icons/icons.generated.tsx'), lines.join('\n'))
console.log(`Generated ${Object.keys(map).length} icons (${bodies.size} Phosphor glyphs, weight ${weight}).`)
